name: Python Flask CI

on:
  pull_request:
    paths:
      - '**/*.py'
      - 'Pipfile'
      - 'Pipfile.lock'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.4'

      - name: Install pipenv
        run: |
          python -m pip install --upgrade pip
          pip install pipenv

      - name: Install dependencies
        run: |
          pipenv install --dev  # Usa --dev si tienes dependencias de desarrollo

      - name: Run tests
        run: |
          pipenv run pytest  # Usa pipenv run para ejecutar tus pruebas
